version: '3.6'
services:

  wordpress:
    image: wordpress:latest
    container_name: wordpress
    volumes:
      - ./wordpress:/var/www/html
    environment:
       WORDPRESS_DB_NAME: DbName
       WORDPRESS_TABLE_PREFIX: wp_
       WORDPRESS_DB_HOST: DbHOST
       WORDPRESS_DB_USER: DbUSER
       WORDPRESS_DB_PASSWORD: DbPASSWORD
       WORDPRESS_CONFIG_EXTRA: |
           define('FS_METHOD', 'direct');
           define( 'AWS_ACCESS_KEY_ID', 'ACCESSKEY');
           define( 'AWS_SECRET_ACCESS_KEY', 'SECRETKEY');
           define( 'DISALLOW_FILE_MODS', true );
           define( 'WP_AUTO_UPDATE_CORE', false );
           define( 'AS3CF_SETTINGS', serialize( array(
            // Storage Provider ('aws', 'do', 'gcp')
           'provider' => 'aws',
           // Bucket to upload files to
<<<<<<< HEAD
           'bucket' => 'letstest',
=======
           'bucket' => 'mybucket',
>>>>>>> e1ef9557bb28eb94d4ffd2e2e5d7e190f18e7f4d
           // Automatically copy files to bucket on upload
           'copy-to-s3' => true,
           // Enable object prefix, useful if you use your bucket for other files
           'enable-object-prefix' => true,
           // Object prefix to use if 'enable-object-prefix' is 'true'
           'object-prefix' => 'wp-content/uploads/',
           ) ) );
<<<<<<< HEAD
=======
          
>>>>>>> e1ef9557bb28eb94d4ffd2e2e5d7e190f18e7f4d
    restart: unless-stopped
    ports:
        - 80:80
        - 443:443

  wp-auto-config:
    image: wpcli
    build: ./
    container_name: wp_autoconfig
    entrypoint: sh -c "chmod -R 777 /var/www/html/wp-content/ && /wait && make -f /scripts/Makefile"
    volumes:
      - ./wordpress:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - wordpress
    environment:
      # Waiting for MySQL and wordpress -------------------
      - WAIT_HOSTS=DbHOST:3306,wordpress:80
      - WAIT_BEFORE_HOSTS=30
      - WAIT_AFTER_HOSTS=15
      - WAIT_HOSTS_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=30
      - WAIT_HOST_CONNECT_TIMEOUT=30
